apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager-query-state
  namespace: flink
  labels:
    app: flink
    component: flink-taskmanager-query-state
spec:
  type: NodePort
  ports:
  - name: query-state
    port: 6125
    targetPort: 6125
    nodePort: 8152
  selector:
    app: flink
    component: taskmanager