FROM flink:1.13.1
ENV TZ Asia/Shanghai
COPY flink-shaded-hadoop-2-uber-2.8.3-10.0.jar /opt/flink/lib
# docker build -t  iregistry.baidu-int.com/acg-iidp/flink:1.13.1 .
# docker push iregistry.baidu-int.com/acg-iidp/flink:1.13.1
