./configure \
            --enable-iodebug \
            --enable-x86-debugger \
            --with-x   \
            --with-x11  \
            --enable-all-optimizations \
            --enable-cpu-level=6 \
            --enable-x86-64 \
            --enable-vmx=2 \
            --enable-pci \
            --enable-usb \
            --enable-usb-ohci \
            --enable-e1000 \
            --enable-debugger \
            --enable-disasm \
            --disable-debugger-gui \
            --prefix=$HOME/bochs

make
make install