{{ if .Values.serviceAccount.bindCluster }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "flink.serviceAccount" . }}-{{ include "flink.clusterRole" . }}
  labels:
    {{- include "flink.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "flink.clusterRole" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "flink.serviceAccount" . }}
  namespace: {{ include "flink.namespace" . }}
{{ end }}