{{ if .Values.taskmanager.stateRest.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flink.taskmanager.service" . }}
  namespace: {{ include "flink.namespace" . }}
  labels:
    {{- include "flink.labels" . | indent 4 }}
    app.kubernetes.io/component: {{ include "flink.taskmanager" . }}
spec:
  type: NodePort
  ports:
  - name: query-state
    port: 6125
    targetPort: 6125
    nodePort: {{ .Values.taskmanager.stateRest.nodePort }}
  selector:
    {{- include "flink.selectorLabels" . | indent 4 }}
    app.kubernetes.io/component: {{ include "flink.jobmanager" . }}
{{ end }}