apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flink.taskmanager" . }}
  namespace: {{ include "flink.namespace" . }}
  labels:
    {{- include "flink.labels" . | indent 4 }}
    app.kubernetes.io/component: {{ include "flink.taskmanager" . }}
spec:
  replicas: {{ .Values.taskmanager.replicas }} #可以扩容
  selector:
    matchLabels:
      {{- include "flink.selectorLabels" . | indent 6 }}
      app.kubernetes.io/component: {{ include "flink.taskmanager" . }}
  minReadySeconds: {{ .Values.taskmanager.autoscaling.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        {{- include "flink.labels" . | indent 8 }}
        app.kubernetes.io/component: {{ include "flink.taskmanager" . }}
    spec:
      containers:
      - name: {{ .Values.taskmanager.container.name }}
        image: {{ .Values.taskmanager.container.image }}
        imagePullPolicy: {{ .Values.taskmanager.container.imagePullPolicy }}
        args: ["taskmanager"]
        ports:
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query-state
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 30
          periodSeconds: 60
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf/
        {{- if .Values.taskmanager.kafka.enable }}
        - name: flink-kafka-config-volume
          mountPath: {{ .Values.taskmanager.kafka.jksPath }}
          readOnly: true
        {{- end }}
        securityContext:
          runAsUser: 9999  # refers to user _flink_ from official flink image, change if necessary
        env:
        - name: FLINK_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccountName: {{ include "flink.serviceAccount" . }}
      volumes:
      - name: flink-config-volume
        configMap:
          name: {{ include "flink.configmap" . }}
          items:
          - key: flink-conf.yaml
            path: flink-conf.yaml
          - key: log4j-console.properties
            path: log4j-console.properties
      {{- if .Values.taskmanager.kafka.enable }}
      - name: flink-kafka-config-volume
        secret:
          secretName: {{ include "flink.taskmanager.kafka" . }}
          items:
          - key: kafka.keystore.jks
            path: {{ .Values.taskmanager.kafka.keystoreName }}
          - key: kafka.truststore.jks
            path: {{ .Values.taskmanager.kafka.truststoreName }}
      {{ end }}