{{ if .Values.flinkConf.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flink.configmap" . }}
  namespace: {{ include "flink.namespace" . }}
  labels: 
    {{- include "flink.labels" . | indent 4 }}
data:
  flink-conf.yaml: |+
    jobmanager.rpc.address: {{ include "flink.jobmanager.service" . }}
    taskmanager.numberOfTaskSlots: {{ .Values.taskmanager.numberOfTaskSlots }}
    blob.server.port: 6124
    jobmanager.rpc.port: 6123
    taskmanager.rpc.port: 6122
    queryable-state.proxy.ports: 6125
    jobmanager.memory.process.size: {{ .Values.jobmanager.memoryProcessSize }}
    taskmanager.memory.process.size:  {{ .Values.taskmanager.memoryProcessSize }}
    parallelism.default: {{ .Values.jobmanager.parallelism }} 
    {{ if and .Values.ha.enable .Values.s3.enable -}} 
    kubernetes.cluster-id: {{ include "flink.clusterId" . }}
    high-availability: org.apache.flink.kubernetes.highavailability.KubernetesHaServicesFactory
    high-availability.storageDir: s3://flink/recovery
    {{ end }}
    {{- if .Values.s3.enable -}} 
    s3.endpoint: {{ .Values.s3.endpoint }}
    s3.path.style.access: true
    s3.access-key: {{ .Values.s3.accessKey }}
    s3.secret-key: {{ .Values.s3.secretKey }}
    {{ end }}
{{ (.Files.Glob "log4j-console.properties").AsConfig | indent 2 }}
{{ end }} 
