apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ekuiper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ekuiper.labels" . | nindent 4 }}
data:
  "kuiper.yaml": |
    {{ $kuiper := index .Values "kuiperConfig" "kuiper.yaml" }}
    {{- toYaml $kuiper | nindent 6 }}