apiVersion: v1
kind: Service
metadata:
  name: {{ include "ekuiper.fullname" . }}-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ekuiper.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - name: ekuiper-manager
    port: 9082
    protocol: TCP
    targetPort:  managerport
    nodePort: {{ default 30000 .Values.manager.nodePort }}
  selector:
    {{- include "ekuiper.selectorLabels" . | nindent 4 }}
