apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: admin
  labels:
    strimzi.io/cluster: kafka-cluster
  namespace: kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        type: allow
        operations:
          - All
      - resource:
          type: group
          name: "*"
          patternType: literal
        type: allow
        operations:
          - All
      - resource:
          type: cluster
          name: "*"
          patternType: literal
        type: allow
        operations:
          - All
      - resource:
          type: transactionalId
          name: "*"
          patternType: literal
        type: allow
        operations:
          - All