apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-cluster
  labels:
    app: hello-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-pod
          image: nigelpoulton/k8sbook:edge
          ports:
            - containerPort: 8080