apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-cluster
  labels:
    app: ubuntu-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ubuntu-pc
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ubuntu-pc
    spec:
      containers:
        - name: ubuntu-pc
          image: zyxrepo/ubuntu-cluster:22.04
          ports:
            - containerPort: 8080