FROM --platform=linux/arm64/v8 alpine:3.20
LABEL org.opencontainers.image.authors="zhangyongxiang@baidu.com"
RUN apk update --no-cache && apk add --no-cache bash tzdata inetutils-telnet curl build-base go musl-dev git openssl openssh
ENV TZ Asia/Shanghai
RUN echo 'Asia/Shanghai' > /etc/timezone
RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
ENTRYPOINT ["tini", "-v", "-g", "--"]

# docker build -t iregistry.baidu-int.com/gbi-enterprise/alpine:arm64-v8-3.20-go -f Dockerfile.arm64_go .
