ARG ARCH=amd64
FROM  --platform=linux/${ARCH} centos:7 AS builder
RUN yum install -y wget && wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
RUN tar -xvf Python-3.9.6.tgz

FROM  --platform=linux/${ARCH} centos:7
LABEL org.opencontainers.image.authors="zhangyongxiang@baidu.com"
# RUN yum update -y && yum groupinstall -y "Development Tools" && yum install -y epel-release openssl-devel bzip2-devel libffi-devel
RUN yum update -y && yum install -y epel-release gcc openssl-devel bzip2-devel libffi-devel make
COPY --from=builder /Python-3.9.6 /Python-3.9.6
# docker commit的方式可以是使用下面的命令
# RUN cd Python-3.9.6 && ./configure --enable-optimizations && make altinstall && cd ..
RUN cd Python-3.9.6 && ./configure && make altinstall && cd ..
RUN rm -rf /Python-3.9.6
RUN yum install -y python3-pip
ENV TZ Asia/Shanghai
RUN localedef -c -i zh_CN -f UTF-8 zh_CN.UTF-8
ENV LC_ALL zh_CN.utf-8
ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_CN:zh
RUN echo 'LANG=zh_CN.UTF-8' > /etc/locale.conf
RUN echo 'Asia/Shanghai' > /etc/timezone
RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY tini /usr/bin/
RUN chmod a+x /usr/bin/tini
ENTRYPOINT ["tini", "-v", "-g", "--"]
# docker build -t zyxrepo/python:3.9.6 -f Dockerfile.centos.3.9 .