apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-example-k8s
  labels:
    app: flink-example-k8s
subjects:
  - kind: ServiceAccount
    name: default
    namespace: flink
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io